spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: s1
              uri: http://localhost:8081
              predicates:
                - Path=/api/customers/**
            - id: s2
              uri: http://localhost:8082
              predicates:
                - Path=/api/products/**